version: '3.4'

services:
  mongodb:
    container_name: mongo.db
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/var/lib/monogodb/data
    networks:
      - tedu_exam
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: Admin@123$$

  sqlserver:
    container_name: sqlserver.db
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - '1433:1433'
    volumes:
      - sqlserver-data:/var/lib/sqlserver/data
    networks:
      - tedu_exam
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Admin@123$$

networks:
  tedu_exam:
    driver: bridge
volumes:
  mongo-data:
  sqlserver-data:
